INSERT INTO tb_videos(ID,nombre,descripcion,fecha_carga,fecha_publicacion,estatus,total_reproducciones,total_vistas,duracion,url,canal_ID)
VALUES 
(601,   "say it right",
	"UMG (en representación de Mosley / Geffen); IMPEL, Anthem Entertainment (Publishing), LatinAutor - SonyATV, LatinAutor, ASCAP, CMRRA, Sony ATV Publishing, BMI - Broadcast Music Inc., Abramus Digital, UNIAO BRASILEIRA DE EDITORAS DE MUSICA - UBEM, Reservoir Media (Publishing), AMRA, SOLAR Music Rights Management, PEDL, Forward Music Publishing Co., Ltd., LatinAutorPerf y 17 sociedades de derechos musicales",
	"2022/02/25","2022/02/25","Disponible",0,0,"03:02", "https://www.youtube.com/watch?v=rCwlf8shQZ4",0),
(602,	"Una prueba simplepararevisar que tambien estan tus ojos",
	"¿Qué tan buena es tu vista? ¿Quieres checar? ¡Tal vez seas una tetracrómata! Es decir, una persona con una visión de color aumentada. Estas tienen más receptores en sus ojos que el resto de la población de la Tierra. Pueden ver más tonos de diferentes colores. Así que, ¿eres un superhumano? ¡Veamos! Esta prueba tiene 4 niveles: simple, regular, difícil y muy complicado. Si llegas al nivel 4, prepárate para un trabajo duro, ¡solo el 6 % de la gente logra pasar! Música por Epidemic Sound https://www.epidemicsound.com/ Materiales de archivo (fotos, grabaciones y otros): ",
	"2022/03/20",	"2022/03/20",	"Disponible",	0,	0,	"08:26",	"https://www.youtube.com/watch?v=xovwOzF6f-4",	0),
(603,	"Animales Metidos con el Enemigo Equivocado",
	"10 Animales Que Se Metieron Con El Oponente Equivocado Cuando te Metes con el Animal Equivocado",
	"2022/01/06",	"2022/01/06",	"Disponible",	0,	0,	"09:05",	"https://www.youtube.com/watch?v=SsFf2Zkv06M",	0),
(604,	"MOMENTOS XD #13",	
	"Estoy de vuelta ",	
	"2021/06/09",	"2021/06/09",	"Disponible",	0,	0,	"09:26",	"https://www.youtube.com/watch?v=UXnxzAJRbVA",	0),
(605,	"MOMENTOS XD #14",	
	"Ya asia falta otro video, después de ese especial 5mil volvemos a la normalidad XD espero les guste este vídeo, al final puse los mismos saludos XD así que habrá saludo doble para alguno pero bueno espero les guste no se olviden de dejar un like Recuerden que ya hay canal de Gameplays, pero antes deben encontrarlo, tranquilos que es más fácil de lo que creen, hay los espero brous",
	"2021/08/15",	"2021/08/15",	"Disponible",	0,	0,	"08:40",	"https://www.youtube.com/watch?v=yMH9Nd8XnYI",	0),
(606,	"MEMES MEXICANOS 26",
	"USA CODIGO ELDED EN RAPPI: https://rappi.app.link/ Puedes ver todo el contenido de este canal primero y en vivo en: http://www.twitch.tv/elded Suscribete: https://goo.gl/fFPrqA Canales de los memes: ElRoxet: https://www.youtube.com/channel/UCTFBxGq41VK1w7DyZG7Tsqg Memes Mexicanos: https://www.youtube.com/c/MemesMexicanos Mi otro canal (elded): https://goo.gl/rjv4px Canal de Noticias (BDNA",
	"2021/09/02",	"2021/09/02",	"Disponible",	0,	0,	"02:57",	"https://www.youtube.com/watch?v=vW91iqT1jNM",	0),
(607,	"SI ME HACES REIR TE DOY 1000€",
	"Like y a la siguiente subo la apuesta Mi Tienda: https://rubiuscorp.com/ Twitch: https://twitch.tv/Rubius Server Discord: https://discord.gg/rubius Twittah: https://twitter.com/Rubiu5 FB: https://www.facebook.com/pages/ElrubiusOMG/337992166223323",
	"2020/11/10",	"2020/11/10",	"Disponible",	0,	0,	"12:25",	"https://www.youtube.com/watch?v=_21FqhKowec",	0),
(608,	"DRAGON BALL SUPER BROLY RAP  PORTA  VIDEO OFICIAL RESUBIDO",
	"Vuelvo a resubir el video del Dragon Ball Super Broly Rap porque TOEI ANIMATION me lo ha bloqueado de nuevo Los videos sumaban más de 70 millones de visitas. Lo subiré tantas veces como sea necesario para que podáis  Soma #PORTA #DRAGONBALLRAP BROLY",
	"2021/08/02",	"2021/08/02",	"Disponible",	0,	0,	"05:17",	"https://www.youtube.com/watch?v=3s32vFlFQvc",	0),
(609,	"PORTERIA CHALLENGE by Rubius",
	"Like para mas trickshots en la vida real :D Y fap si somos lamentablas jugando al futbol lol Twittah: https://twitter.com/Rubiu5 FB: https://www.facebook.com/pages/ElrubiusOMG/337992166223323 Google+: https://plus.google.com/u/0/b/117842212651500158292/117842212651500158292/posts Suscribete! :D http://www.youtube.com/user/elrubiusOMG",
	"2017/08/12",	"2017/08/12",	"Disponible",	0,	0,	"06:41",	"https://www.youtube.com/watch?v=ERpNI7lkvA4",	0),
(610,	"COSAS QUE SOLO PASAN EN JAPON",
	"Like por el cafe de Ricardo Parte 2 pronto! Twitch: https://twitch.tv/Rubius Server Discord: https://discord.gg/eaBHEju Twittah: https://twitter.com/Rubiu5 FB: https://www.facebook.com/pages/ElrubiusOMG/337992166223323",
	"2017/08/12",	"2017/08/12",	"Disponible",	0,	0,	"01:10",	"https://www.youtube.com/watch?v=5ddTrPPXByM",	0),
(611,	"ME HAGO PASAR POR BOT  Hide and Seek GMOD",
	"Like por la musica de Youtuber de 2012 Discord: https://discord.gg/rubius Mi Tienda: https://rubiuscorp.com Streams: https://www.twitch.tv/Rubius",
	"2021/07/31",	"2021/07/31",	"Disponible",	0,	0,	"12:53",	"https://www.youtube.com/watch?v=YkPvm5Vsklo",	0),
(612,	"Si no es Parada NO Paro",
	"Mira el Sketch acá  https://youtu.be/wYW1LkUxZQw El Bus, tú, yo y los olores más extraños de la vida. Piénsalo  Si este video te resultó muy reciclado, mira los nuevos en nuestro canal principal: https://www.youtube.com/enchufetv/  enchufe.tv - Todos los derechos reservados por Touché Films 2022.",
	"2022/02/22",	"2022/02/22",	"Disponible",	0,	0,	"10:47",	"https://www.youtube.com/watch?v=Jm6gbBIqfW0",	0),
(613,	"Carnaval con Amigos",
	"Un carnaval con amigos no tiene precio, a menos que seas el que pone la gasolina  Si este video te resultó muy reciclado, mira los nuevos en nuestro canal principal: https://www.youtube.com/enchufetv/ enchufe.tv - Todos los derechos reservados por Touché Films 2022.",
	"2022/02/28",	"2022/02/28",	"Disponible",	0,	0,	"09:03",	"https://www.youtube.com/watch?v=FtxHCgQmTNU",	0),
(614,	"Nos reimosw del peligro",
	"Mira el nuevo sketch https://youtu.be/xq9puCijArU Nuestros criminales no son de cuello blanco pero solo porque no se bañan Si este video te resultó muy reciclado, mira los nuevos en nuestro canal principal: https://www.youtube.com/enchufetv/  enchufe.tv - Todos los derechos reservados por Touché Films 2022",
	"2022/03/22",	"2022/03/22",	"Disponible",	0,	0,	"09:54",	"https://www.youtube.com/watch?v=CPotyfDsjok",	0),
(615,	"Algo del Toque Femenino",
	"PREGUNTA SERIA: Cuando una mujer dice no pasa nada ¿Qué significa?  Si este video te resultó muy reciclado, mira los nuevos en nuestro canal principal: https://www.youtube.com/enchufetv/  enchufe.tv - Todos los derechos reservados por Touché Films 2022.",
	"2022/03/19",	"2022/03/19",	"Disponible",	0,	0,	"10:37",	"https://www.youtube.com/watch?v=UmqbfmsDD2o",	0),
(616,	"Feliz Navidad Inmundo Animal",
	"Ya huele a decepción por regalos y peleas familiares, qué linda es la navidad  #EnchufeEnTNT #EspecialEnchufe #TNT ¡likea! https://www.facebook.com/enchufetv ¡stalkea! https://www.instagram.com/enchufetv enchufe.tv - Todos los derechos reservados por Touché Films 2020.",
	"2021/12/25",	"2021/12/25",	"Disponible",	0,	0,	"11:29",	"https://www.youtube.com/watch?v=Z0EHfFZ9JpU",	0),
(617,	"Tipos de Alumnos | enchufetv",
	"¿En este ecosistema, qué ameba eres tú? Mira más #NationalEnchugraphic aquí: https://youtube.com/playlist?list=PLlGSQJ04OGkiwdfHdOlzdDZmhTcD7-G0F #SketchEnchufetv #enchufetv ¡twittea! https://twitter.com/enchufetv ¡likea! https://www.facebook.com/enchufetv ¡Unidad Educativa William Shakespeare School (http://bit.ly/WilliamShakespeareSchool) acolitó a Enchufe.tv y por eso son chéveres!. Un vídeo nuevo cada semana.  enchufe.tv - Todos los derechos reservados por Touché Films 2021.",
	"2014/09/15",	"2014/09/15",	"Disponible",	0,	0,	"04:35",	"https://www.youtube.com/watch?v=X8Q4vPKDMpk",	0),
(618,	"Acrobatic Gymnastics Competition in Burgas 2016",
	"Este arroz esta riquísimo y es ideal para fiestas como Semana Santa que por costumbre evitamos comer carne, además se hace muy fácil y rápido, vas a triunfar en un día de fiesta si preparas este arroz pero también para cualquier día de la semana lo puedes hacer porque utilizando productos congelados el precio es mucho más asequible y (si tienes la suerte que tengo yo que mi vecino me regala estos estupendos cangrejos aún mejor), un arroz caldoso de sabor intenso a marisco y que rinde mucho, te lo recomiendo, ¡pruébalo te encantara!",
	"2021/01/18",	"2021/01/18",	"Disponible",	0,	0,	"04:34",	"https://youtu.be/bOBZBjCWDWM",	0),
(619,	"Musica Instrumental De Los Años 70 y 80 - Instrumentales Del Recuerdo Lo Mejor",
	"Musica Instrumental De Los Años 70 y 80 - Instrumentales Del Recuerdo Lo Mejor ¿Ya sabes? La música es una medicina para el alma y la salud. Muchos estudios han demostrado que escuchar la música adecuada le brindará muchos beneficios diferentes, tales como: mejorar la memoria, la capacidad de concentrarse, reducir el estrés, ayudarlo a ser ",
	"2020/09/20",	"2020/09/20",	"Disponible",	0,	0,	"02:02",	"https://youtu.be/SQiPHZHe5xw",	0),
(620,	"Aprende los Colores - Video Educativo para Niños!",
	"Aprende los Colores - Video Educativo para Niños!",
	"2018/04/24",	"2018/04/24",	"Disponible",	0,	0,	"07:52",	"https://youtu.be/V0cfA32ekOc",	0),
(621,	"Estrellita ¿Dónde estás? y Más Canciones para Dormir Plim Plim Canciones Infantiles",
	"Plim Plim es un conjunto de contenidos para un público global pensado para bebés y niños en edad pre-escolar. Con una revolucionaria e innovadora forma de transmitir mensajes positivos llega al corazón de los niños del mundo. Promoción de los Valores humanos, primeros hábitos y respeto por el medio ambiente son las banderas de nuestro héroe que llega para hacer de la infancia un mundo mágico. Plim Plim es un producto global que repara en cada detalle de ",
	"2018/02/24",	"2018/02/24",	"Disponible",	0,	0,	"03:18",	"https://youtu.be/0e9IQNt0iZc",	0),
(622,	"VIDEOS SATISFACTORIOS Música Relajante para DORMIR RÁPIDO Relájate en pocos SEGUNDOS",
	"Merlin Symphonic Distribution (en representación de MOR Records); Hexacorp (music publishing), Polaris Hub AB, Create Music Publishing y 5 sociedades de derechos musicale",
	"2020/05/26",	"2020/05/26",	"Disponible",	0,	0,	"11:27",	"https://youtu.be/7UFWbyOk5Nc",	0),
(623,	"No eligas el jabón equivocado Slime Challenge Dont choose the wrong soap!! SaneuB By Las Ratitas",
	"No eligas el jabón equivocado Slime Challenge Don't choose the wrong soap slime Challenge",
	"2018/12/08",	"2018/12/08",	"Disponible",	0,	0,	"12:36",	"https://youtu.be/YZhMnZkDYwE",	0),
(624,	"TV de perro! Videos para entretener a los perros con música relajante!",
	"TV de perro! Videos para entretener a los perros con música relajante! - Combate el aburrimiento de tus perros fácilmente y rápidamente con esta relajante TV para perros combinada con la música más calmada y relajante para prevenir la hiperactividad y la ansiedad.",
	"2019/03/25",	"2019/03/25",	"Disponible",	0,	0,	"02:00",	"https://youtu.be/avj3i65DUL0",	0),
(625,	"LIT killah - La Trampa es Ley (Official Video)",
	"LIT killah - La Trampa es Ley Suscribite al canal » https://LitKillah.lnk.to/suscripcion",
	"2022/02/10",	"2022/02/10",	"Disponible",	0,	0,	"02:30",	"https://www.youtube.com/watch?v=qyc07COpZDQ",	0),
    (626,	"10 cosas que los gatos odian y debes evitar",
	"¿Te gusta conocer datos curiosos sobre los felinos? En este vídeo de ExpertoAnimal te traemos una recopilación de 100 curiosidades sobre los gatos. Descubre un montón de datos, peculiaridades y curiosidades sobre el comportamiento, el carácter y la anatomía de los gatos",
	"2020/09/19",	"2020/09/19",	"Disponible",	0,	0,	 "08:31",	"https://youtu.be/1d4ZZzYtY04",	0),
(627,	"10 COSAS RARAS que hacen los GATOS",
	"En este vídeo de gatos super monos, os vamos a enseñar cuáles son las 10 cosas raras que hacen los GATOS, seguro que alguna de ellas lo hace el tuyo. SI quieres conocer más cosas sobre los gatos no te pierdas este vídeo y pasa un buen rato con un vídeo de GATOS CHISTOSOS. En experto animal",
	"2017/07/16",	"2017/07/16",	"Disponible",	0,	0,	"04:01",	"https://youtu.be/ltmLUXiGKPM",	0),
(628,	"¿Por qué mi gato frota su cara contra la mía? - ¡AQUÍ LA RESPUESTA!",
	"¿Tu gato frota su cara contra la tuya y no entiendes por qué lo hace? Debes saber que se trata de un comportamiento natural de la especie que realiza con miembros u objetos que quiere marcar como parte de su territorio o grupo de confianza. De esta forma, si tu gato se frota contra ti, o contra tus piernas, está haciendo justamente esto, marcarte e identificarte. Pero esto no es todo, en este vídeo de ExpertoAnimal te explicamos por qué tu gato frota su cara contra la tuya más en profundidad. Y si quieres descubrir más curiosidades sobre los gatos o el comportamiento felino, pásate por nuestro canal",
	"2019/02/01",	"2019/02/01",	"Disponible",	0,	0,	"02:49",	"https://youtu.be/wDIKsGWoH0o",	0),
(629,	"El Baile del Sapito - Las Canciones Dela Granja - Canciones infantiles dela granja",
	"El Baile del Sapito - Las Canciones Dela Granja - Canciones infantiles dela granja",
	"2017/05/11",	"2017/05/11",	"Disponible",	0,	0,	"03:21",	"https://youtu.be/_yv6Gx0gljs",	0),
(630,	"24Datos geniales que quizá no conozcas",
	"Alguna vez ha experimentado esto después de haber estado usando algo durante muchos años, descubriste que tenía otras características útiles Como un pequeño detalle al que ni siquiera le prestaste atención, resultó tener un significado y un propósito importante",
	"2020/02/17",	"2020/02/17",	"Disponible",	0,	0,	"09:31",	"https://youtu.be/1Mf16Cv7UCs",	0),
(631,	"Si tu cuerpo puede hacer eso, eres uno entre un millón",
	"¿Qué hace a tu cuerpo especial? ¡Bueno, pues todo! Todos los cuerpos humanos tienen características únicas y sofisticadas. Tu cuerpo puede incluso hacer trucos: ¡aproximadamente 1/3 de la gente puede levantar una ceja! Muy pocas personas consiguen lamerse los codos. ¿Y si estás entre los que puede hacer escritura especular sin esfuerzo? Échale un vistazo a esta lista de trucos corporales poco comunes y quizá te reconozcas en alguno de ellos. La animación fue creada por Genial.",
	"2021/09/27",	"2021/09/27",	"Disponible",	0,	0,	"08:48",	"https://youtu.be/InOQCsn_Xvc",	0),
(632,	"Inspirational Heartland Gymnastics coach and gymnast duo",
	"This is a fantastic video of how much a coach can impact the love of a sport. Ms. Kassie is the owner of Heartland Gymnastics in Cape Girardeau Missouri.",
	"2021/01/10",	"2021/01/10",	"Disponible",	0,	0,	"12:52",	"https://youtu.be/pgiHBkVw800",	0),
(633,	"Acrobatic Gymnastics Competition in Burgas 2016",
	"This is a video-reportage from a National Competition Young acrobat in Burgas (Bulgaria) 11.12.16. We took 3 place! Thanks to my partners in the trio — Siana Vylkova and Nikol Stoyanova, as well as my amazing coaches — Pavlinka Stankova and Yordan Mihaylov. Also big thanks to my friends for their support. We all worked hard!",
	"2017/01/08",	"2017/01/08",	"Disponible",	0,	0,	"04:51",	"https://youtu.be/Vkg1QkUgYwI",	0),
(634,	"World Championships in Gymwheel 2016 Team Final Israel Liron Di Castro Straight line",
	"Gimnasia en una rueda - Gymnastic Wheel",
	"2016/09/11",	"2016/09/11",	"Disponible",	0,	0,	"03:28",	"https://youtu.be/5ntqiGLJeAU?list=RDVkg1QkUgYwI",	0),
(635,	"Vendes chicles Y ese PAQUE...Bromas en la calle - Bufones.net",
	"En esta ocasión Mary hizo una broma donde le decía halagos a hombres para ver sus reacciones",
	"2018/03/04",	"2018/03/04",	"Disponible",	0,	0,"04:50",	"https://youtu.be/eHwZ6RYr6Ww?list=RDVkg1QkUgYwI",	0),
(636,	"Tostada de huevo con queso y jamon",
	"Yummy boy siempre está tratando de hacer un buen video.",
	"2020/05/03",	"2020/05/03",	"Disponible",	0,	0,	"05:44",	"https://youtu.be/eXBrn5wvl4A",	0),
(637,	"Cómo hacer patatas fritas crujientes",
	"Este es un canal donde puedes encontrar platos deliciosos con recetas fáciles.",
	"2021/05/21",	"2021/05/21",	"Disponible",	0,	0,	"04:13",	"https://youtu.be/p-oVufdc3W8",	0),
(638,	"hamburguesa de tocino hecha a mano",
	"Comida callejera en profundidad y no aburrida",
	"2018/10/13",	"2018/10/13",	"Disponible",	0,	0,	"06:00",	"https://youtu.be/8AYPhibsCqc",	0),
(639,	"Tacos de Tripa al disco",
	"Uno de mis tacos favoritos para disfrutar después de la fiesta...Taquitos de tripa al disco con salsa roja molcajeteada.",
	"2020/08/26",	"2020/08/26",	"Disponible",	0,	0,	"10:47",	"https://youtu.be/Ytx1XqZrgW4",	0),
(640,	"Probando COMIDA CALLEJERA EN CHINA",
	"Nunca había sorprendido tanto a mi paladar",
	"2017/04/13",	"2017/04/13",	"Disponible",	0,	0,	"11:12",	"https://youtu.be/Cq_KA3VVN-4",	0),
(641,	"Visitando un SUPERMERCADO EN CHINA",
	"Desde dulces deliciosos hasta tortugas por kilo... Bienvenido a LuisiToooops...",
	"2017/03/30",	"2017/03/30",	"Disponible",	0,	0,	"11:48",	"https://youtu.be/XvrngnRhOis",	0),
(642,	"Diputado del PAN cuenta travesía en transporte público para llegar al AIFA",
	"El diputado local del PAN, Aníbal Cañez Morales, describió todo el recorrido que realizó para llegar al aeropuerto en Santa Lucía",
	"2020/03/21",	"2020/03/21",	"Disponible",	0,	0,	"01:25",	"https://youtu.be/uKdurbthiE4",	0),
(643,	"Se registra derrumbe en pared del Cañón del Sumidero",
	"La Secretaria de Medio Ambiente y Recursos Naturales, María Luisa Albores González, recordó que en una consulta ciudadana ganó el proyecto Yo prefiero el lago, por lo que hoy se declara como Área Natural Protegida",
	"2022/03/22",	"2022/03/22",	"Disponible",	0,	0,	"02:30",	"https://youtu.be/WolBHeIRu8Y",	0),
(644,	"Amenazan de muerte a periodistas que cubrían funeral de Armando Linares",
	"Reporteros que cubrían el funeral de Armando Linares, periodista asesinado en Michoacán, fueron amenazados de muerte en el lugar, Que nos fuéramos o íbamos a valer ver",
	"2021/03/16",	"2021/03/16",	"Disponible",	0,	0,	"07:09",	"https://youtu.be/g_ccio7-RPQ",	0),
(645,	"Solo Para Borrachos / Musica De Cantina - Ramon Ayala, Cadetes, Palominos, Cachorros y mas",
	"Como la Cantina Vol.2",
	"2020/04/24",	"2020/04/24",	"Disponible",	0,	0,	"01:04",	"https://youtu.be/zfn7DlHQ3ho",	0),
(646,	"COMO EN LA CANTINA, VOL. 1",
	"Como la Cantina Vol.",
	"2017/05/12",	"2017/05/12",	"Disponible",	0,	0,	"02:04",	"https://youtu.be/bOBZBjCWDWM",	0),
(647,	"Balea a conductora que le chocó - Inseguridad - En Punto con Denise Maerker",
	"Un incidente de tránsito termina con el asesinato de una conductora de Uber, en Tijuana, Baja California",
	"2018/01/27",	"2018/01/27",	"Disponible",	0,	0,	"02:27",	"https://youtu.be/oBHl2CvU4IU",	0),
(648,	"Tu elección revelará la verdad sobre ti",
	"Los rasgos de personalidad no son constantemente estables, pueden cambiar. Pero, a pesar de eso, incluso las cosas más pequeñas pueden revelar qué tipo de persona eres. Por ejemplo, tu forma de caminar es una posible indicadora de tu nivel de vulnerabilidad, mientras que la manera en que cuelgas el papel higiénico puede decir mucho de tu asertividad.",
	"2018/10/30",	"2018/10/30",	"Disponible",	0,	0,	"07:47",	"https://youtu.be/QiRulOnLi7E",	0),
(649,	"Qué dice el mes en que naciste sobre ti Test de personalidad",
	"Los tests de personalidad son graciosos y curiosos, y dicen algunas cosas sobre quién eres. Aquí tienes un nuevo examen de personalidad que puedes tomar desde Internet. Dime qué día naciste ¡y te revelaré tu personalidad oculta! Este test analiza el día, mes y hora de tu nacimiento e interpreta los resultados. Cada uno de los días de un mes tiene una lectura diferente que refleja los rasgos de la personalidad de una persona que haya nacido ese día.",
	"2018/06/29",	"2018/06/29",	"Disponible",	0,	0,	"11:19",	"https://youtu.be/5SIRuZd44lk",	0),
(650, "PROBANDO COMIDA MILITAR",
	"Bueno gente el día de hoy les traigo un nuevo vídeo de la vez que estuvimos comiendo comida militar, comida toxica la verdad, pero si te gusto mi sufrimiento no olviden dejar su like y suscribiéndose para ver mas vídeos mamalones como este.",
	"2022/03/14",	"2022/03/14", "Disponible",	0,	0,	"21:58",	"https://www.youtube.com/watch?v=RKvPCQwmm_A",	0);

